# Generated by Django 5.2.4 on 2025-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.CharField(default='mylogo.png', max_length=50),
        ),
    ]
